coverage_service: cobertura_xml
workspace: ios-base.xcworkspace
xcodeproj: ios-base.xcodeproj
scheme: ios-base-develop
binary_basename: ios-base-Debug
ignore:
  - Pods/*
  - ios-base/Extensions/UIImageExtension.swift
  - R.generated.swift
  - ios-base/AppDelegate.swift
