pipeline {
    agent { label 'mac' }
    stages {
        stage('CI') {
            environment {
                SLACK_CHANNEL = '#ios-base'
                S3_BUCKET = 'ios-base-files'
                AWS_DEFAULT_REGION = 'us-east-1'
                AWS_ACCESS_KEY = credentials('aws-s3-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-s3-secret-access-key')
            }
            stages{
                stage('bundle'){
                    steps{
                        sh 'sudo gem cleanup'
                        sh 'bundle update'
                        sh 'bundle install --path ./vendor/bundle'
                    }
                }                
                stage('test'){
                    steps {
                        sh 'pod install'
                        sh 'fastlane ios test'
                    }
                }
                stage('package'){
                    when {
                        expression { BUILD_QA }
                    }
                    steps {
                        sh 'fastlane ios build_qa'
                        sh "aws s3 cp iosbase-debug.ipa s3://${env.S3_BUCKET}/qa_builds/${env.GIT_COMMIT}/iosbase-debug.ipa"
                        slackSend channel: "${env.SLACK_CHANNEL}", message: "A new IPA file has been uploaded for QA: https://s3.us-east-1.amazonaws.com/${env.S3_BUCKET}/qa_builds/${env.GIT_COMMIT}/iosbase-debug.ipa"
                    }
                }
            }
        }
        stage('Release') {
            stages{
                stage('release Beta') {
                    when {
                        branch 'develop'
                        expression { TARGET == 'staging'}
                    }
                    steps {
                        sh 'fastlane ios release_staging'
                        echo 'Send slack notification'
                    }
                }
                stage('release Production') {
                    when {
                        anyOf {
                            branch 'develop'
                            branch 'master'
                            tag "release-*"
                        }
                        expression { TARGET == 'prod' }
                    }
                    steps {
                        sh 'fastlane ios release_production'
                        echo 'Send slack notification'
                    }
                }
            }
        }
    }
}