pipeline {
    agent { label 'mac' }
    environment {
        APP_NAME = 'ios-base'
        SLACK_CHANNEL = '#ios-base'
        S3_BUCKET = 'ios-base-files'
        AWS_DEFAULT_REGION = 'us-east-1'
        AWS_ACCESS_KEY = credentials('aws-s3-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-s3-secret-access-key')
    }
    stages {
        stage('bundle'){
            steps{
                sh 'sudo gem cleanup'
                sh 'sudo bundle update'
                sh 'bundle install --path ./vendor/bundle'
            }
        }                
        stage('test'){
            steps {
                sh 'pod install'
                sh 'fastlane ios test'
            }
        }
        stage('package Debug'){
            when {
                branch 'qa' or branch 'develop'
            }            
            steps {
                sh 'fastlane ios build_develop'
                sh "aws s3 cp ${env.APP_NAME}.ipa s3://${env.S3_BUCKET}/develop/${env.GIT_COMMIT}/${env.APP_NAME}-Debug.ipa"
                slackSend channel: "${env.SLACK_CHANNEL}", message: "A new Debug build was completed for ${env.GIT_COMMIT}-${env.GIT_BRANCH}. IPA file has been uploaded for QA: https://s3.us-east-1.amazonaws.com/${env.S3_BUCKET}/develop/${env.GIT_COMMIT}/${env.APP_NAME}-Debug.ipa"
            }
        }
        stage('package Staging'){
            when {
                branch 'staging'
            }            
            steps {
                sh 'fastlane ios release_staging'
                sh "aws s3 cp ${env.APP_NAME}.ipa s3://${env.S3_BUCKET}/staging/${env.GIT_COMMIT}/${env.APP_NAME}-Staging.ipa"
                slackSend channel: "${env.SLACK_CHANNEL}", message: "A new Beta build was pushed to TestFlight for ${env.GIT_COMMIT}-${env.GIT_BRANCH}. See ${env.BUILD_URL}/console for detailed output"
            }
        }
        stage('release Production') {
            when {
                branch 'master'
            }
            steps {
                sh 'fastlane ios release_production'
                slackSend channel: "${env.SLACK_CHANNEL}", message: "A new Production build was pushed to TestFlight for ${env.GIT_COMMIT}-${env.GIT_BRANCH}. See ${env.BUILD_URL}/console for detailed output"
            }
        }
    }
}