pipeline {
    agent { label 'mac' }
    environment {
        APP_NAME = 'ios-base'
        SLACK_CHANNEL = '#ios-base'
    }    
    stages {
        stage('release Beta') {
            when {
                branch 'develop'
            }
            steps {
                sh 'fastlane ios release_staging'
                slackSend channel: "${env.SLACK_CHANNEL}", message: "A new Staging build was pushed to TestFlight for ${env.GIT_COMMIT}-${env.GIT_BRANCH}. See ${env.BUILD_URL}/console for detailed output"
            }
        }
        stage('release Production') {
            when {
                branch 'master'
            }
            steps {
                sh 'fastlane ios release_production'
                slackSend channel: "${env.SLACK_CHANNEL}", message: "A new Production build was pushed to TestFlight for ${env.GIT_COMMIT}-${env.GIT_BRANCH}. See ${env.BUILD_URL}/console for detailed output"
            }
        }
    }
}